version: "3.9"
services:
  # Backend
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mern-ecommerce
      - NODE_ENV=docker
    env_file:
      - ./api/.env
    networks:
      - test

  # mongodb:
  #   image: mongo
  #   restart: always
  #   networks:
  #     - test
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - ./database:/data/db

networks:
  test:
    external: true
